language: android

jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-21
    - extra-android-m2repository
    - extra-android-support

script: ./gradlew build

notifications:
  email: false
