language: android

jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.0 rc2
    - android-22
    - extra-android-m2repository
    - extra-android-support

script: ./gradlew build

notifications:
  email: false
