sudo: false

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-22
    - extra-android-m2repository
    - extra-android-support

script: ./gradlew build

notifications:
  email: false
