sudo: false

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:
  - cd $TRAVIS_BUILD_DIR/..
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O ndk.bin
  - chmod a+x ndk.bin
  - ./ndk.bin > /dev/null
  - rm ndk.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export PATH=$PATH:$ANDROID_NDK_HOME
  - echo $PATH

before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone -b dmach https://github.com/simonnorberg/pd-for-android.git pd-for-android
  - cd pd-for-android
  - git submodule update --init --recursive
  - ./gradlew PdCore:assembleRelease

script:
  - cd $TRAVIS_BUILD_DIR
  - ./gradlew build

notifications:
  email: false
